import { StyleSheet } from "react-native";
import { COLORS, FONTFAMILY } from "../../../constants";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.WHITE },
  gradient: { flex: 1, position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  header: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 16,
    marginBottom: 10,
  },
  headerTitle: {
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    fontSize: 16,
    color: COLORS.BLACK,
    fontWeight: "600",
  },
  supportText: {
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.RED,
    fontWeight: "500",
  },
  card: {
    backgroundColor: COLORS.BUTTON_BACKGROUND,
    borderRadius: 16,
    marginHorizontal: 16,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    marginBottom: 24,
    elevation: 1,
  },
  sectionTitle: {
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    fontSize: 20,
    color: COLORS.BOTTOM_BLACK,
    fontWeight: "700",
    marginBottom: 16,
  },
  statusWrapper: {
    position: "relative",
  },
  statusContainer: {
    marginBottom: 12,

  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 2,
  },
  statusTitle: {
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    fontWeight: "600",
    fontSize: 16,
    color: COLORS.TEXT_SECONDARY,
    marginLeft: 8,
  },
  statusTime: {
    fontFamily: FONTFAMILY.INTER_REGULAR,
    fontWeight: "400",
    fontSize: 14,
    color: COLORS.INPUT_TEXT,
    marginLeft: 28,
  },
  verticalDottedLine: {
    position: "absolute",
    left: 10,
    top: 22,
    height: 28,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 1,
  },
  dot: {
    width: 2.5,
    height: 2.5,
    borderRadius: 1.25,
    backgroundColor: COLORS.GRAY,
    marginVertical: 3,
  },
  vendorHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  vendorInfo: {
    flex: 1,
    minWidth: 0,
  },
  vendorName: {
    fontFamily: FONTFAMILY.INTER_BOLD,
    fontSize: 20,
    color: COLORS.TEXT_PRIMARY,
    fontWeight: "700",
    flex: 1,
    width: '75%',
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  vendorLocation: {
    fontSize: 12,
    color: COLORS.TEXT_GRAY,
    marginLeft: 4,
    fontFamily: FONTFAMILY.INTER_REGULAR,
    fontWeight: "400",
    flexShrink: 1,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 0.2,
    justifyContent: 'flex-end',
    paddingRight: 12,
    width: '20%',
  },
  ratingText: {
    color: COLORS.ACCENT,
    marginLeft: 4,
    fontSize: 16,
    fontWeight: "400",
    fontFamily: FONTFAMILY.INTER_REGULAR,
  },
  qtyBox: {
    backgroundColor: COLORS.BORDER_INPUT,
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 4,
    marginRight: 8,
    borderWidth: 0,
  },
  qtyText: {
    fontSize: 14,
    color: COLORS.BLACK,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    fontWeight: "500",
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16
  },
  itemText: {
    fontSize: 14,
    color: COLORS.BOTTOM_BLACK,
    fontFamily: FONTFAMILY.INTER_REGULAR,
    fontWeight: "400",
  },
  rupee: {
    fontSize: 14,
    color: COLORS.BOTTOM_BLACK,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    fontWeight: "600",
    textAlign: 'right',
    flex: 1
  },
  orderId: {
    fontFamily: FONTFAMILY.INTER_REGULAR,
    fontWeight: "400",
    fontSize: 12,
    color: COLORS.GRAY,

  },
  billRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  billLabel: {
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    fontWeight: "600",
    color: COLORS.LOGIN_SUBTITLE,
    fontSize: 14,
  },
  billValue: {
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    fontWeight: "600",
    color: COLORS.LOGIN_SUBTITLE,
  },
  grandTotalLabel: {
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    fontWeight: "600",
    color: COLORS.BLACK,
  },
  grandTotalValue: {
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    fontWeight: "600",
    color: COLORS.BLACK,
  },
  offerLabel: {
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    fontWeight: "500",
    color: COLORS.THEME_GREEN,
  },
  offerValue: {
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    fontWeight: "500",
    color: COLORS.THEME_GREEN,
  },
  toPayLabel: {
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    fontWeight: "600",
    fontSize: 15,
    color: COLORS.BLACK,
  },
  toPayValue: {
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    fontWeight: "600",
    fontSize: 15,
    color: COLORS.BLACK,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.TEXT_MUTED,
    marginVertical: 12,
  },
  detailRow: { flexDirection: "row", alignItems: "center", },
  detailLabel: {
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    fontWeight: "500",
    color: COLORS.BOTTOM_BLACK,
    marginLeft: 6,
    fontSize: 16,
  },
  detailValue: {
    fontFamily: FONTFAMILY.INTER_REGULAR,
    fontWeight: "400",
    color: COLORS.GRAY,
    marginLeft: 26,
    fontSize: 14,
  },
  buttonsContainer: {
    flexDirection: "row",
    marginHorizontal: 16,
    marginBottom: 24,
    gap: 12,
  },
  rateBtn: {
    flex: 1,
    borderColor: COLORS.THEME_GREEN,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: "center",
    paddingVertical: 12,
    backgroundColor: COLORS.WHITE,
  },
  rateBtnText: {
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    fontWeight: "600",
    fontSize: 16,
    color: COLORS.ACCENT,
  },
  invoiceBtn: {
    flex: 1,
    backgroundColor: COLORS.THEME_GREEN,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    flexDirection: "row",
    gap: 8,
  },
  invoiceBtnText: {
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    fontWeight: "600",
    fontSize: 16,
    color: COLORS.WHITE,
  },
});