import { StyleSheet, Dimensions } from 'react-native';
import { COLORS, FONTFAMILY } from '../../../constants/colors';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  card: {
    backgroundColor: COLORS.BUTTON_BACKGROUND,
    borderRadius: 16,
    padding: 16,
    marginTop: 0, // i removed this to align with the top of the screen
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 24,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    color: COLORS.BLACK,
    fontWeight: '700',
    marginBottom: 16,
  },
  inputContainer: {
    marginBottom: 16,
  },
  addressContainer: {
    marginBottom: 16,
  },
  addressLabel: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.INPUT_TEXT,
    marginBottom: 8,
  },
  asterisk: {
    color: COLORS.BLACK,
  },
  addressInputContainer: {
    marginTop: 0,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
    borderRadius: 16,
    paddingHorizontal: 12,
    backgroundColor: COLORS.CARD_BACKGROUND,
    minHeight: 80,
  },
  addressInput: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_REGULAR,
    color: COLORS.BLACK,
    textAlignVertical: 'top',
    minHeight: 40,
  },
  locationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 8,
  },
  locationButtonText: {
    fontSize: 14,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.THEME_GREEN,
    fontWeight: '500',
  },
  uploadSection: {
    marginBottom: 20,
  },
  uploadLabel: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.INPUT_TEXT,
    marginBottom: 12,
  },
  uploadButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
    borderRadius: 16,
    paddingVertical: 16,
    backgroundColor: COLORS.CARD_BACKGROUND,
    gap: 8,
    height: 80
  },
  uploadText: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_REGULAR,
    color: COLORS.INPUT_TEXT,
    fontWeight: '400'
  },
  uploadedFileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: COLORS.CARD_BACKGROUND,
  },
  uploadedFileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  uploadedFileName: {
    fontSize: 14,
    fontFamily: FONTFAMILY.INTER_REGULAR,
    color: COLORS.BLACK,
    flex: 1,
  },
  removeButton: {
    padding: 4,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.LIGHT_GRAY,
    marginVertical: 24,
  },
  switchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingVertical: 8,
    backgroundColor: COLORS.CARD_BACKGROUND,
    borderRadius: 16,
    paddingHorizontal: 16,

    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
  },
  switchLabel: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.INPUT_TEXT,
    flex: 1,
    marginRight: 12,
    fontWeight: '500'
  },
  repeatContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.LIGHT_GRAY,
    backgroundColor: COLORS.CARD_BACKGROUND,
    borderRadius: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
  },
  repeatLabel: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.INPUT_TEXT,
    fontWeight: '500',
  },
  repeatValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    justifyContent: 'flex-end',
  },
  repeatValue: {
    fontSize: 14,
    fontFamily: FONTFAMILY.INTER_REGULAR,
    color: COLORS.INPUT_TEXT,
    fontWeight: '400',
    flexShrink: 1,
    textAlign: 'right',
    marginStart: 20
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: COLORS.WHITE,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    width: '100%',
    maxHeight: '90%',
    overflow: 'hidden',
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.LIGHT_GRAY,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    color: COLORS.BLACK,
    fontWeight: '700',
    flex: 1,
  },
  closeButton: {
    padding: 4,
  },
  selectedTimesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: COLORS.CARD_BACKGROUND,
    marginTop: 16,
    borderRadius: 12,
    gap: 12,
  },
  selectedTimeBox: {
    flex: 1,
    alignItems: 'center',
  },
  selectedTimeLabel: {
    fontSize: 12,
    fontFamily: FONTFAMILY.INTER_REGULAR,
    color: COLORS.LOGIN_SUBTITLE,
    marginBottom: 4,
    fontWeight: '400',
  },
  selectedTimeValue: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    color: COLORS.THEME_GREEN,
    fontWeight: '600',
  },
  selectedTimePlaceholder: {
    color: COLORS.LOGIN_SUBTITLE,
    fontWeight: '400',
  },
  timeSeparator: {
    paddingHorizontal: 8,
  },
  timeSeparatorText: {
    fontSize: 18,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.LOGIN_SUBTITLE,
    fontWeight: '500',
  },
  selectionIndicator: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: COLORS.BUTTON_BACKGROUND,
    marginTop: 12,
    borderRadius: 8,
  },
  selectionIndicatorText: {
    fontSize: 14,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.THEME_GREEN,
    fontWeight: '500',
    textAlign: 'center',
  },
  timePickerContainer: {
    marginTop: 16,
  },
  timePickerContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  timeSection: {
    marginBottom: 24,
  },
  timeSectionTitle: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    color: COLORS.BLACK,
    fontWeight: '600',
    marginBottom: 12,
    paddingLeft: 4,
  },
  timeGrid: {
    gap: 8,
  },
  hourRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 8,
  },
  timeOption: {
    flex: 1,
    backgroundColor: COLORS.CARD_BACKGROUND,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.BORDER_INPUT,
    minHeight: 48,
    justifyContent: 'center',
  },
  selectedTimeOption: {
    backgroundColor: COLORS.THEME_GREEN,
    borderColor: COLORS.THEME_GREEN,
    shadowColor: COLORS.THEME_GREEN,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  timeOptionText: {
    fontSize: 13,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.BLACK,
    fontWeight: '500',
  },
  selectedTimeOptionText: {
    color: COLORS.WHITE,
    fontWeight: '700',
  },
  modalButtonRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 20,
    marginTop: 16,
  },
  modalCancelButton: {
    flex: 1,
    backgroundColor: COLORS.THEME_GREEN,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: COLORS.THEME_GREEN,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  modalCancelButtonText: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    color: COLORS.WHITE,
    fontWeight: '600',
  },
  modalResetButton: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.BORDER_INPUT,
  },
  modalResetButtonText: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.LOGIN_SUBTITLE,
    fontWeight: '500',
  },
  // Repeat Days Bottom Sheet Styles
  repeatSheetContent: {
    padding: 16,

  },
  repeatSheetTitle: {
    fontSize: 20,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    color: COLORS.TEXT_PRIMARY,
    fontWeight: '700',
    marginBottom: 24,
    textAlign: 'left'
  },
  repeatDayItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
    backgroundColor: COLORS.CARD_BACKGROUND,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER_INPUT,
  },

  repeatDayLabel: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.INPUT_TEXT,
    fontWeight: '500',
  },
  repeatCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
    backgroundColor: COLORS.WHITE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  repeatCheckboxSelected: {
    backgroundColor: COLORS.THEME_GREEN,
  },
  repeatSheetButtonContainer: {
    marginTop: 24,
    paddingHorizontal: 0,
  },
  repeatSaveButton: {
    backgroundColor: COLORS.THEME_GREEN,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    width: '100%',
  },
  repeatSaveButtonDisabled: {
    opacity: 0.5,
  },
  repeatSaveButtonText: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.WHITE,
    fontWeight: '500',
  },
  // Time Picker Bottom Sheet Styles
  timePickerSheetContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 20,
  },
  timePickerSheetTitle: {
    fontSize: 20,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    color: COLORS.BLACK,
    fontWeight: '700',
    marginBottom: 20,
    textAlign: 'center',
  },
  timePickerButtonRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  timePickerResetButton: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.BORDER_INPUT,
  },
  timePickerResetButtonText: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    color: COLORS.LOGIN_SUBTITLE,
    fontWeight: '500',
  },
  timePickerCancelButton: {
    flex: 1,
    backgroundColor: COLORS.THEME_GREEN,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  timePickerCancelButtonText: {
    fontSize: 16,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    color: COLORS.WHITE,
    fontWeight: '600',
  },
  errorText: {
    fontSize: 12,
    fontFamily: FONTFAMILY.INTER_REGULAR,
    color: COLORS.ERROR,
    marginTop: 4,
    marginLeft: 4,
  },
});

