import { StyleSheet } from 'react-native';
import { COLORS, FONTFAMILY } from '../../../constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: 16,
    width: '100%',
  },
  toolbarContainer: {
    flex: 1,
  },
  supportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  supportText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.ERROR_TOAST,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    marginLeft: 6,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 24,
  },
  serviceCard: {
    backgroundColor: COLORS.CARD_BACKGROUND,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
  },
  serviceCardTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    marginBottom: 8,
  },
  timelineContainer: {
    marginTop: 8,
  },
  timelineItemContainer: {
    marginBottom: 0,
  },
  timelineContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  timelineIconContainer: {
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderBoxIconContainer: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  completedIconContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.BORDER_INPUT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  completedIcon: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.TEXT_PRIMARY,
  },
  activeStatusContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.CARD_BACKGROUND,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
  },
  activeStatusIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#007AFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineTextContainer: {
    flex: 1,
  },
  timelineStatusText: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    marginBottom: 4,
  },
  timelineDateText: {
    fontSize: 14,
    fontWeight: '400',
    color: COLORS.INPUT_TEXT,
    fontFamily: FONTFAMILY.INTER_REGULAR,
  },
  timelineLineContainer: {
    flexDirection: 'column',
    marginLeft: 12,
    height: 25,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  timelineDash: {
    width: 2,
    height: 3,
    backgroundColor: COLORS.TEXT_GRAY,
  },
  orderInfoCard: {
    backgroundColor: COLORS.CARD_BACKGROUND,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
  },
  orderIdRow: {
    marginBottom: 12,
  },
  orderIdText: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  locationText: {
    fontSize: 12,
    fontWeight: '400',
    color: COLORS.TEXT_GRAY,
    fontFamily: FONTFAMILY.INTER_REGULAR,
    marginLeft: 6,
  },
  separatorLine: {
    width: '100%',
    height: 1,
    backgroundColor: COLORS.SEPARATOR,
    marginBottom: 12,
  },
  itemDetailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemDetailsLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  quantityBadge: {
    backgroundColor: COLORS.BORDER_INPUT,
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityBadgeText: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.BLACK,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
  },
  serviceTypeText: {
    fontSize: 16,
    fontWeight: '400',
    color: COLORS.THEME_GREEN,
    fontFamily: FONTFAMILY.INTER_REGULAR,
  },
  serviceTypeMargin: {
    marginLeft: 8,
  },
  arrowIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 4,
  },
  itemDetailsRight: {
    alignItems: 'center',
  },
  itemPrice: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
  },
  billCard: {
    backgroundColor: COLORS.BUTTON_BACKGROUND,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  billCardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    marginBottom: 4,
  },
  billCardSubtitle: {
    fontSize: 12,
    fontWeight: '500',
    color: COLORS.NOTE_TEXT,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
    marginBottom: 16,
  },
  billRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  billLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.LOGIN_SUBTITLE,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    flex: 1,
  },
  billLabelUnderlined: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.LOGIN_SUBTITLE,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    flex: 1,
    textDecorationLine: 'underline',
  },
  billValue: {
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
  },
  billDivider: {
    height: 1,
    backgroundColor: COLORS.SEPARATOR,
    marginBottom: 12,
  },
  grandTotalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
  },
  grandTotalValue: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
  },
  customerCard: {
    backgroundColor: COLORS.CARD_BACKGROUND,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.BORDER_INPUT,
  },
  customerCardTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTFAMILY.INTER_SEMIBOLD,
    marginBottom: 16,
  },
  customerRow: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
  },
  customerLabel: {
    fontSize: 16,
    fontWeight: '400',
    color: COLORS.NOTE_TEXT,
    fontFamily: FONTFAMILY.INTER_REGULAR,
    marginRight: 8,
  },
  customerValue: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTFAMILY.INTER_MEDIUM,
  },
});

